spring:
  config:
    activate:
      on-profile: dev

  datasource:
    url: jdbc:postgresql://localhost:5432/discodeit
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    org.hibernate.SQL: debug
