spring:
  application:
    name: discodeit
  datasource:
    url: jdbc:postgresql://localhost:5432/discodeit
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate       # 개발에선 편하게
    show-sql: false
    defer-datasource-initialization: true
    properties:
      hibernate:
        format_sql: true

  sql:
    init:
      mode: never
      platform: postgresql   # ⬅️ data-postgresql.sql만 실행
      schema-locations: classpath:schema.sql
      data-locations: classpath:data-postgresql.sql

logging:
  level:
    root: info
    # 웹 요청 로그
    org.springframework.web: info
    org.springframework.web.filter.CommonsRequestLoggingFilter: info

    # 직접 작성한 코드
    com.sprint.mission.discodeit: info

management:
  metrics:
    enable:
      cache: true

