# Requires: SPRING_DATASOURCE_URL, SPRING_DATASOURCE_USERNAME, SPRING_DATASOURCE_PASSWORD

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/discodeit}
    username: ${SPRING_DATASOURCE_USERNAME:discodeit}
    password: ${SPRING_DATASOURCE_PASSWORD:discodeit}

server:
  port: 8080
  error:
    include-stacktrace: on_param
    include-message: always
  compression:
    enabled: false # Disabled for easier debugging of raw responses

logging:
  level:
    root: INFO
    com.sprint.mission: DEBUG
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
    net.ttddyy.dsproxy.listener: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
