server:
  port: 8080

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/discodeit
    username: postgres
    password: 1234
  jpa:
    hibernate:
      ddl-auto: create-drop

  boot:
    admin:
      client:
        url: ${SPRING_BOOT_ADMIN_CLIENT_URL}

logging:
  level:
    root: info
    com.discodeit: debug
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace
    org.springframework.security: TRACE

management:
  endpoint:
    health:
      show-details: always
  info:
    env:
      enabled: true