spring:
  application:
    name: discodeit
  profiles:
    active: dev   # 기본은 dev

  servlet:
    multipart:
      maxFileSize: 10MB
      maxRequestSize: 30MB

  jpa:
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

logging:
  level:
    root: info
    com.sprint.mission.discodeit: info
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace

discodeit:
  storage:
    type: local
    local:
      root-path: .discodeit/storage

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,loggers
  endpoint:
    health:
      show-details: always

info:
  app:
    name: Discodeit
    version: 1.7.0
  java:
    version: 17
  spring-boot:
    version: 3.4.0
  settings:
    datasource:
      url: ${spring.datasource.url}
      driver: ${spring.datasource.driver-class-name}
    jpa:
      ddl-auto: ${spring.jpa.hibernate.ddl-auto}
    storage:
      type: ${discodeit.storage.type}
      path: ${discodeit.storage.local.root-path}
    multipart:
      max-file-size: ${spring.servlet.multipart.maxFileSize}
      max-request-size: ${spring.servlet.multipart.maxRequestSize}