spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/discodeit
    username: postgres
    password: 1234
  jpa:
    hibernate:
      ddl-auto: validate

logging:
  level:
    root: info   # 운영은 info
    com.discodeit: info

info:
  datasource:
    url: ${DEV.DB_URL}
    ddl-auto: validate
  storage:
    type: local
    path: ${STORAGE_ROOT_PATH}