spring:
  config:
    import: optional:file:.env[.properties]
  profiles:
    active: local
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
        default_batch_fetch_size: 100
  jackson:
    time-zone: UTC
    serialization:
      write-dates-as-timestamps: false
    default-property-inclusion: non_null
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

server:
  shutdown: graceful
  compression:
    enabled: true

logging:
  level:
    org.hibernate.SQL: OFF
    net.ttddyy.dsproxy.listener: OFF

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
