spring:
  datasource:
    url: jdbc:h2:mem:discodeit-test;MODE=PostgreSQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop

logging:
  level:
    com.sprint.mission: DEBUG
    net.ttddyy.dsproxy.listener: DEBUG

management:
  endpoint:
    health:
      show-details: always

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false

discodeit:
  storage:
    type: LOCAL
    local:
      root-path: ./build/test-storage
      orphan-grace: 2s
