server:
  port: 0

spring:
  datasource:
    url: jdbc:h2:mem:testdb;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;DB_CLOSE_DELAY=-1
    username: sa
    password:
    driver-class-name: org.h2.Driver

  h2:
    console:
      enabled: false

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    show-sql: false

  sql:
    init:
      mode: never

logging:
  level:
    com.sprint.mission.discodeit: debug
    org.springframework.test: info
    org.springframework.boot.test: info
    org.hibernate: warn
    org.springframework.web: warn
    root: warn

storage:
  local:
    root-path: ./test-uploads

management:
  endpoints:
    web:
      exposure:
        include: health

springdoc:
  swagger-ui:
    enabled: false
  api-docs:
    enabled: false