spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/discodeit}
    username: ${POSTGRES_USER:discodeit_user}
    password: ${POSTGRES_PASSWORD:discodeit1234}
  jpa:
    hibernate:
      ddl-auto: validate

server:
  port: 8080
  error:
    include-stacktrace: on_param
    include-message: always
  compression:
    enabled: false

logging:
  level:
    com.sprint.mission: DEBUG
    org.springframework.web: DEBUG
    net.ttddyy.dsproxy.listener: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

discodeit:
  datasource-proxy:
    name: DS-Proxy-Local
    log-level: DEBUG
    slow-query-threshold: 5s
    slow-query-log-level: WARN
