spring:
  datasource:
    url: jdbc:h2:mem:testdb;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;DEFAULT_NULL_ORDERING=HIGH;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: create-drop  # 테스트마다 깨끗하게
    show-sql: false

  sql:
    init:
      mode: always
      platform: h2           # ⬅️ data-h2.sql만 실행

  h2:
    console:
      enabled: false