openapi: 3.0.3
info:
  title: Discodeit API
  version: "1.0.0"
servers:
  - url: /api/auth

paths:
  /login:
    $ref: "./paths/auth.yaml#/login"
  /logout:
    $ref: "./paths/auth.yaml#/logout"

components:
  schemas:
    UserResponse:
      $ref: "./schemas/user.yaml#/UserResponse"
    LoginRequest:
      $ref: "./schemas/auth.yaml#/LoginRequest"
    LogoutRequest:
      $ref: "./schemas/auth.yaml#/LogoutRequest"
