openapi: 3.0.3
info:
  title: Discodeit Users API
  version: "1.0.0"
  description: 사용자(User) 관련 API 문서
servers:
  - url: /api/users
paths:
  /:
    $ref: "./paths/users.yaml#/users_root"
  /{id}:
    $ref: "./paths/users.yaml#/user_by_id"
components:
  schemas:
    UserResponse:
      $ref: "./schemas/user.yaml#/UserResponse"
    UserCreateRequest:
      $ref: "./schemas/user.yaml#/UserCreateRequest"
    UserSaveResponse:
      $ref: "./schemas/user.yaml#/UserSaveResponse"
    UserUpdateRequest:
      $ref: "./schemas/user.yaml#/UserUpdateRequest"
    ApiError:
      $ref: "./schemas/error.yaml#/ApiError"
