openapi: 3.0.3
info:
  title: Discodeit Auth API
  version: "1.0.0"
  description: 인증(Auth) 관련 API 문서
servers:
  - url: /api/auth
paths:
  /login:
    $ref: "./paths/auth.yaml#/login"
  /logout:
    $ref: "./paths/auth.yaml#/logout"
components:
  schemas:
    UserSaveResponse:
      $ref: "./schemas/user.yaml#/UserSaveResponse"
    LoginRequest:
      $ref: "./schemas/auth.yaml#/LoginRequest"
    LogoutRequest:
      $ref: "./schemas/auth.yaml#/LogoutRequest"
