openapi: 3.0.3
info:
  title: Discodeit Binary Contents API
  version: "1.0.0"
  description: 첨부 파일(Binary Content) 관련 API 문서
servers:
  - url: /api/binary-contents
paths:
  /:
    $ref: "./paths/binary-contents.yaml#/binary_contents_root"
  /{id}:
    $ref: "./paths/binary-contents.yaml#/binary_content_by_id"
components:
  schemas:
    UserResponse:
      $ref: "./schemas/binary-content.yaml#/BinaryContentResponse"
