openapi: 3.0.3
info:
  title: Discodeit Users API
  version: "1.0.0"
  description: 사용자(User) 관련 API 문서
servers:
  - url: /api
paths:
  /users:
    $ref: "./paths/users.yaml#/usersRoot"
  /users/{userId}:
    $ref: "./paths/users.yaml#/userById"
components:
  parameters:
    UserId:
      in: path
      name: userId
      required: true
      schema:
        type: string
        format: uuid
    Username:
      in: query
      name: username
      schema:
        type: string
        minLength: 2
        maxLength: 32
        pattern: "^(?!.*\\.\\.)[A-Za-z0-9._]+$"
      description: |-
        **username**과 일치하는 사용자를 검색합니다.
        
        - 요청 시 대소문자 모두 허용되지만,
        - 서버에서 strip 후 소문자로 정규화하여 처리됩니다.
    Email:
      in: query
      name: email
      schema:
        type: string
        format: email
        minLength: 6
        maxLength: 254
      description: |-
        **email**과 일치하는 사용자를 검색합니다.
        
        - 요청 시 대소문자 모두 허용되지만,
        - 서버에서 strip 후 소문자로 정규화하여 처리됩니다.
  schemas:
    UserResponse:
      $ref: "./schemas/user.yaml#/UserResponse"
    UserCreateRequest:
      $ref: "./schemas/user.yaml#/UserCreateRequest"
    UserSaveResponse:
      $ref: "./schemas/user.yaml#/UserSaveResponse"
    UserUpdateRequest:
      $ref: "./schemas/user.yaml#/UserUpdateRequest"
    ApiError:
      $ref: "./schemas/error.yaml#/ApiError"
