openapi: 3.0.3
info:
  title: Discodeit Binary Contents API
  version: "1.0.0"
  description: 첨부 파일(Binary Content) 관련 API 문서
servers:
  - url: /api
paths:
  /binaryContents:
    $ref: "./paths/binaryContents.yaml#/binaryContentsRoot"
  /binaryContents/{binaryContentId}:
    $ref: "./paths/binaryContents.yaml#/binaryContentById"
components:
  parameters:
    binaryContentIds:
      in: query
      name: binaryContentIds
      description: 조회할 첨부 파일 ID 목록
      required: true
      schema:
        type: array
        items:
          type: string
          format: uuid
        minItems: 1
    binaryContentId:
      in: path
      name: binaryContentId
      description: 조회할 첨부 파일 ID
      required: true
      schema:
        type: string
        format: uuid
  schemas:
    BinaryContentDto:
      $ref: "./schemas/binaryContent.yaml#/BinaryContentDto"
