spring:
  profiles:
    active: dev

  boot:
    admin:
      client:
        instance:
          name: discodeit

#  datasource:
#    driver-class-name: org.postgresql.Driver
#    url: jdbc:postgresql://localhost:5432/discodeit
#    username: postgres
#    password: 1234



