#spring.application.name=discodeit

# application.yaml
spring:
  profiles:
    active: jcf   # jcf | file

#이 부분은 아직 잘 모르겠음.
discodeit:
  repository:
    type: jcf   # jcf | file
    file-directory: .discodeit


